excluded:
  - Example/Pods
disabled_rules:
  - unused_closure_parameter
  - large_tuple
  - multiple_closures_with_trailing_closure
  - trailing_comma
opt_in_rules:
  - force_unwrapping
  - explicit_init
  - overridden_super_call
  - redundant_nil_coalescing
  - nimble_operator
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument
  - literal_expression_end_indentation
  - joined_default_parameter
  - contains_over_first_not_nil
  - override_in_extension
  - single_test_class
  - sorted_first_last
  - convenience_type
  - empty_count
  - empty_string
  - toggle_bool
  - unused_private_declaration
  - identical_operands
  - array_init
  - implicit_return
  - implicitly_unwrapped_optional
  - vertical_whitespace_closing_braces
  - last_where
  - redundant_type_annotation
  - strict_fileprivate

empty_count: warning
force_cast: warning

line_length:
  ignores_function_declarations: true

custom_rules:
  already_true:
    regex: "== true"
    message: "Don't compare to true, just use the bool value."
  already_bool:
    regex: "== false"
    message: "Don't compare to false, just use !value."
  numbers_smell:
    regex: '(return |case |\w\(|: |\?\? |\, |== |<=? |>=? |\+= |\-= |\/= |\*= |%= |\w\.\w+ = )\(*\d{2,}'
    message: "Numbers smell; define a constant instead."
  auto_generated_leftovers:
    regex: 'func [^\n]*\{\n(\s*super\.[^\n]*\n(\s*\/\/[^\n]*\n)*|(\s*\/\/[^\n]*\n)+)\s*\}'
    message: "Delete auto-generated functions that you don't use"
